"""Traces database of the mappr pipeline"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/06_db_traces.ipynb.

# %% auto 0
__all__ = ['Trace', 'TraceDB']

# %% ../nbs/06_db_traces.ipynb 2
from pathlib import Path
from fastcore.all import *
from fastlite import database

# %% ../nbs/06_db_traces.ipynb 4
class Trace:
    id: int
    timestamp: str
    event: str
    report_id: str
    stage: str
    framework: str
    framework_category: str
    framework_theme_id: str
    data: dict

# %% ../nbs/06_db_traces.ipynb 5
class TraceDB:
    def __init__(self, db_path=None):
        if db_path is None:
            # db_path = Path.home() / cfg.dirs.data / "traces.db"
            db_path = Path.home() / ".evaluatr/data/traces.db"
            
        self.db = database(db_path)
        self.traces = self.db.create(Trace, pk='id', transform=True)

# %% ../nbs/06_db_traces.ipynb 6
@patch
def delete_stage_traces(self:TraceDB, report_id, stage):
    self.db.execute("DELETE FROM traces WHERE report_id=? AND stage=?", [report_id, stage])
